[profile.default]
src = "src"
out = "out"
libs = ["lib"]
dotenv = "../.env"  # Load .env from project root
remappings = [
    "@chainlink=lib/chainlink-brownie-contracts",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"
]

# Optimizer settings  
via_ir = true
optimizer = true
optimizer_runs = 800  # Higher runs = smaller deployment size

# RPC endpoints
[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Optional alternative profile without Yul IR, in case some deployments were built without it
[profile.no_ir]
via_ir = false
optimizer = true
optimizer_runs = 200
